idf_component_register(
  SRCS
  "main.cpp"
  "BleServer.cpp"
  "GpsService.cpp"
  "gps_gatt_def.cpp"
  "ActiveLook.cpp"
  "BleManager.cpp"
  "LoggerService.cpp"
  "EspNowMobile.cpp"
  INCLUDE_DIRS
  "../include"
  REQUIRES
  bt
  nvs_flash
  esp_driver_uart
  log
  freertos
  spiffs
  esp_wifi
  esp_netif
  esp_event)
